export const actionTypes = {
    GENERATE_QR_INFO: 'GENERATE_QR_INFO',
    CHANGE_STYLE: 'CHANGE_STYLE',
    CHANGE_CORRECT_LEVEL: 'CHANGE_CORRECT_LEVEL',
    CREATE_PARAM: 'CREATE_PARAM',
    CHANGE_PARAM: 'CHANGE_PARAM'
}
