export const actionTypes = {
    GENERATE_QR_INFO: 'GENERATE_QR_INFO',
    CHANGE_STYLE: 'CHANGE_STYLE',
    CHANGE_CORRECT_LEVEL: 'CHANGE_CORRECT_LEVEL',
    CREATE_PARAM: 'CREATE_PARAM',
    CHANGE_PARAM: 'CHANGE_PARAM',
    LOAD_DOWNLOAD_DATA: 'LOAD_DOWNLOAD_DATA',
    CHANGE_TITLE: 'CHANGE_TITLE',
    CHANGE_ICON: 'CHANGE_ICON'
}
