

export const prompts: string[] = [
  "marine life, ocean creatures, sea animals, undersea world, aquatic ecosystem, coral reef, deep ocean, sea world, aqua life, marine species",
  "starry sky, galaxy, universe, space, nebula, constellation, milky way, cosmos, night sky, celestial",
  "abstract art, non-representative, non-figurative, abstract expressionism, cubist, modern art, geometric, minimalism, surreal, avant-garde ",
  "wildlife, wild animals, fauna, beasts, safari, jungle, natural habitat, ecosystem, wilderness, animals",
  "cityscape, night view, city lights, skyscrapers, city at night, urban scenery, downtown, skyline, metropolis, neon lights",
  "ancient roman architecture, coliseum, pantheon, roman ruins, classical, columns, arches, roman art, roman empire, basilica",
  "native american totem, tribal art, indians, shaman, spiritual symbols, indigenous, totem pole, native culture, tribal, folklore",
  "stone carving, engraving, relief, bas-relief, stele, sculpture, rock art, lithography, petroglyphs, chiseling",
  "autumn leaves, fall colors, autumn season, foliage, crisp air, harvest, autumnal, fallen leaves, golden autumn, season change",
  "winter landscape, snowfall, snowflakes, snow-covered, frost, winter scene, snowy weather, white winter, snowscape, cold season",
  "3D geometry, polygons, geometric shapes, solids, 3D figures, shapes in space, geometric modeling, spatial geometry, trigonometry, prism",
  "ancient egyptian hieroglyphs, pictorial script, inscription, pharaoh, egyptology, ankh, pyramids, scribes, rosetta stone, cartouche",
  "countryside, pastoral scenery, rural landscape, farms, fields, greenery, pastoral, rolling hills, country life, rustic",
  "van gogh's starry night, post-impressionism, swirling stars, art masterpiece, starry, expressionist, night sky, celestials, cosmos, van gogh",
  "fashion trends, style, latest fashion, vogue, chic, couture, modish, glamour, trendsetter, haute couture",
  "fairy magic, enchanted, sprites, fantasy, mystic, spellbound, charm, pixie, fairyland, elf mythical",
  "fairy-tale town, quaint village, charming, picturesque, idyllic, cobblestone streets, storybook, fable, folklore, enchanting",
  "popular cartoons, animated characters, anime, animation, cartoonist, comic strip, kids show, toons, caricature, manga",
  "retro posters, vintage, old-fashioned, classic billboard, nostalgia, mid-century, antique, past era, elderly, yesteryear",
  "ink wash painting, oriental art, calligraphy, brushwork, Zen art, sumi-e, Chinese painting, ink and wash, traditional Asian art, literati painting",
  "multicolored, colorful, vibrant, diverse, hues, shades, tints, rainbow colors, vivid, technicolor",
  "poker card designs, clubs, diamonds, hearts, spades, face cards, deck of cards, playing cards, joker, royal flush",
  "marvel heroes, superhero, comics, avengers, iron man, captain America, hulk, thor, black widow, spiderman",
  "portrait painting, fine art, sitter, oil painting, profile, canvas, realism, self-portrait, likeness, figure painting",
  "jazz music elements, saxophone, rhythm, blue notes, improvisation, swing, bebop, jazz standards, musical, syncopation",
  "ancient Greek mythology, Olympus, Zeus, Athena, Aphrodite, classical myths, titans, Hercules, mythology, minotaur",
  "succulents, cacti, aloe, desert plants, botanical, flora, fleshy plants, garden, drought-tolerant, exotics",
  "folk embroidery, needlework, stitchery, handicraft, threadwork, crewel, cross-stitch, embroidery pattern, folk art, craft",
  "diamond facets, gemstone, sparkle, jewel, carats, clarity, brilliance, gem-cutting, precious stone, jeweler",
  "ancient Roman sculpture, statue, marble, busts, roman gods, classical, romanesque, roman art, carvings, relief",
  "dance moves, ballet, salsa, breakdance, waltz, tango, jazz dance, ballroom, choreography, dance steps",
  "forest sprites, fairies, fantasy, woodland creatures, nature spirits, magical beings, enchantment, pixies, forest magic, woodland",
  "love elements, hearts, romance, affection, love symbols, sweetheart, love sign, valentine, affectionate, amour",
  "precision instruments, microscope, telescope, precision tools, equipment, laboratory, spectroscopy, microscope, precision measurement, scientific instrument",
  "balloon scenery, hot air balloon, balloon ride, aerial view, balloons in the sky, flight, flying, balloon festival, high altitude, airship",
  "Buddhist art, Buddha, mandala, enlightenment, bodhisattva, Zen, dharma, sutra, Dalai Lama, Buddhist symbols ",
  "Victorian style, antique, prudish, gothic revival, queen victoria, ornate, victorian fashion, 19th century, vintage, victorian architecture",
  "film elements, cinema, directors cut, hollywood, screenplay, box office, camera angles, movie stars, film reel, blockbuster",
  "steampunk, Victorian, retro-futuristic, gears, goggles, steam engine, alternative history, clockwork, anachronistic, industrial revolution",
  "classical sculpture, statue, marble, Greek gods, classical, renaissance, roman art, carvings, relief, busts",
  "virtual reality, VR, augmented reality, virtual world, hologram, VR gaming, simulation, immersive technology, cyberspace, 3D world",
  "marine adventure, pirates, treasure, shipwreck, ocean exploration, sea voyage, nautical, diving, sea monsters, sailing",
  "technology lines, digital, futuristic, tech graphics, circuitry, binary, streamline, data streams, virtual, hi-tech",
  "Christmas elements, Santa Claus, Christmas tree, reindeer, ornaments, snowman, yuletide, festive, bells, presents",
  "African tribal culture, tribe, rituals, masks, African art, tribal dance, tribal music, folklore, ancestors, indigenous",
  "Amusement park, attractions, theme parks, roller coaster, ferris wheel, flower, fountain, outdoor, blue sky",
  "wandering, mystical forest, enchanted, trees, moss, soft light, magic, path, foliage, mysterious",
  "beachside, cozy cottage, sand, seashells, white picket fence, inviting, homey, ocean view",
  "picnic, cherry blossom tree, spring, petals, grass, blanket, soft light, leisure, outdoors, flowers",
  "empty theater stage, after the show, quiet, spotlight, curtains, performance, atmosphere, solitude",
  "river surrounded by trees, blue sky and cumulonimbus, camping, Riverside, in shadow, arbor, light reflecting in the river, tree shade, sunbeams",
  "majestic cliffside, overlooking the ocean, vast seascape, dramatic sky, waves, panoramic view, wind",
  "fantasy, castle and town, castle town, beautiful building, how people live, flowers, trees, nature, romantic, shopping street, street stall, blue sky",
  "broken glass, peeled walls, jungle, city, city center, building, moss, ivy, blue sky, cumulonimbus, collapsed town, broken town, deserted town, roots crawling on walls, outdoor, rubble, ruins",
  "whimsical art gallery, paintings, sculptures, colorful, creative, inspiring, dreamy, imaginative",
  "Giant trees, leaves that cover the sky, maple leaves, Autumn leaves, autumn, red mountain, Fallen leaves, waterfall",
  "back alley, bricks, gangland, wall text graffiti, messy town, gang, shutters, darksome, spooky, dangerous atmosphere, badness, midnight, night, night road, fluorescent lamp",
  "beautiful ballet performance, elegant, dancers, stage, fluid movement, grace, spotlight",
  "trolling, lavender field, fragrant, summer, purple, calming, warm breeze, picturesque, rows, nature",
  "ancient tomb excavation, archeology, hieroglyphics, sarcophagus, dusty, mysterious, historical",
  "outdoor, yoga, zen, harmony, nature, balance pose, peaceful",
  "waterfall, hidden, lush jungle, greenery, mist, tranquil, cascading water, ferns, rocks, nature",
  "dark sky, dense fog, thunderstorm , heavy rain, waves crashing, lighthouse, beacon of light, coastal, rugged",
  "coastal village, peaceful harbor, boats, fishing nets, sea breeze, quaint homes, shoreline",
  "mysterious cave exploration, unknown, torchlight, stalactites, subterranean, hidden treasures, darkness",
  "old-fashioned, street café, nostalgic, city, cobblestone, chairs, tables, people, relaxing, architecture",
  "Visual impact , spooky, imagination, glitch art, revolve round, fluorescent , Fibonacci spiral , galaxy, extreme detailed effect, Lightning and body Interweave, milky way, goddess"
]